// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Prob001 = require("../../src/001/Prob001.bs.js");

describe("Prob001", (function () {
        Jest.test("given 10, the function returns 23", (function (param) {
                return Jest.Expect[/* toEqual */12](23, Jest.Expect[/* expect */0](Prob001.f(10)));
              }));
        Jest.test("given 15, the function returns 35", (function (param) {
                return Jest.Expect[/* toEqual */12](45, Jest.Expect[/* expect */0](Prob001.f(15)));
              }));
        return Jest.test("given 1000, the function returns 233168", (function (param) {
                      return Jest.Expect[/* toEqual */12](233168, Jest.Expect[/* expect */0](Prob001.f(1000)));
                    }));
      }));

/*  Not a pure module */
