// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function fib(number) {
  if (number !== 0) {
    if (number !== 1) {
      return fib(number - 1 | 0) + fib(number - 2 | 0) | 0;
    } else {
      return 1;
    }
  } else {
    return 0;
  }
}

function f(number) {
  var $$break = false;
  var current = 0;
  var res = 0;
  while(!$$break) {
    if (fib(current) >= number) {
      $$break = true;
    } else {
      if (fib(current) % 2 === 0) {
        res = res + fib(current) | 0;
      }
      current = current + 1 | 0;
    }
  };
  return res;
}

exports.fib = fib;
exports.f = f;
/* No side effect */
