// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Prob002 = require("../../src/002/Prob002.bs.js");

describe("Prob002", (function () {
        return Jest.test("Given 4 million, the function returns the correct number", (function (param) {
                      return Jest.Expect[/* toEqual */12](4613732, Jest.Expect[/* expect */0](Prob002.f(4000000)));
                    }));
      }));

/*  Not a pure module */
