// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Prob003 = require("../../src/003/Prob003.bs.js");

describe("Prob003", (function () {
        Jest.test("Given 13195, the function returns 29", (function (param) {
                return Jest.Expect[/* toEqual */12](5, Jest.Expect[/* expect */0](Prob003.f(10)));
              }));
        Jest.test("Given 13195, the function returns 29", (function (param) {
                return Jest.Expect[/* toEqual */12](29, Jest.Expect[/* expect */0](Prob003.f(13195)));
              }));
        return Jest.Skip[/* test */0]("Given 600851475143, the function returns 6857", (function (param) {
                      return Jest.Expect[/* toEqual */12](6857, Jest.Expect[/* expect */0](Prob003.f(-443946297)));
                    }));
      }));

/*  Not a pure module */
