// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function getMultiples(number) {
  return $$Array.of_list(List.sort(Caml_obj.caml_compare, List.filter((function (x) {
                          return Caml_int32.mod_(number, x) === 0;
                        }))($$Array.to_list($$Array.init(number - 2 | 0, (function (x) {
                                return x + 2 | 0;
                              }))))));
}

function f(_number) {
  while(true) {
    var number = _number;
    var multiples = getMultiples(number);
    if (multiples.length > 1) {
      _number = Caml_array.caml_array_get(multiples, multiples.length - 1 | 0);
      continue ;
    } else {
      return number;
    }
  };
}

exports.getMultiples = getMultiples;
exports.f = f;
/* No side effect */
