// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");

function f(number) {
  return List.fold_left((function (x, y) {
                return x + y | 0;
              }), 0, List.filter((function (x) {
                      if (x % 3 === 0) {
                        return true;
                      } else {
                        return x % 5 === 0;
                      }
                    }))($$Array.to_list($$Array.init(number, (function (x) {
                            return x;
                          })))));
}

exports.f = f;
/* No side effect */
